### ISSUE TITLE
MSVC 19.29 Complaining about the _ini suffix

### ISSUE THREAD

**Issue by b1scoito** [tcsullivan/ini-config#1]
I'm running Visual Studio 2019 with MSVC `19.29.30136` and Visual C++ Latest (Already tried on C++20).

![image](https://user-images.githubusercontent.com/17802984/143668171-bb2ef4e5-8f0b-451b-8a85-ca4417183662.png)

**Comment by tcsullivan** [comment]
Yes, I'm not surprised MSVC is having issues. It often appears to be behind in supporting the newer standards.

I don't use MSVC though, only occasionally in Compiler Explorer to check in on its progress with things like this. So until MSVC catches up, there's really not much I can do. If you find a potential fix, let me know.

I'll be more clear in the README too: I said the code is tested on gcc and clang, but it should really read as "this code is only supported on gcc and clang."
